# Generated by Django 3.1.3 on 2023-06-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='content',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_grade',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choice',
            name='text',
            field=models.CharField(default='question text', max_length=550),
        ),
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(default='question text', max_length=550),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='question title', max_length=550),
        ),
    ]
